CREATE TYPE public.app_role AS ENUM ('admin', 'moderator', 'user');

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role public.app_role NOT NULL,
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

CREATE POLICY "Users can read own roles"
ON public.user_roles FOR SELECT TO authenticated
USING (user_id = auth.uid());

CREATE TABLE public.locus_objects (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_index integer NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  locus_slug text NOT NULL,
  glb_path text NOT NULL,
  room text NOT NULL,
  slot_index integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT locus_objects_card_index_positive CHECK (card_index >= 1),
  CONSTRAINT locus_objects_slot_index_valid CHECK (slot_index IS NULL OR slot_index >= 0)
);
GRANT SELECT ON public.locus_objects TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.locus_objects TO authenticated;
GRANT ALL ON public.locus_objects TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.locus_objects_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.locus_objects_id_seq TO service_role;
ALTER TABLE public.locus_objects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read locus objects"
ON public.locus_objects FOR SELECT TO anon, authenticated
USING (true);

CREATE POLICY "Admins insert locus objects"
ON public.locus_objects FOR INSERT TO authenticated
WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins update locus objects"
ON public.locus_objects FOR UPDATE TO authenticated
USING (public.has_role(auth.uid(), 'admin'))
WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins delete locus objects"
ON public.locus_objects FOR DELETE TO authenticated
USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Public read locus object files"
ON storage.objects FOR SELECT TO anon, authenticated
USING (bucket_id = 'locus-objects');

CREATE POLICY "Admins upload locus object files"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'locus-objects'
  AND public.has_role(auth.uid(), 'admin')
  AND lower(storage.extension(name)) = 'glb'
);

CREATE POLICY "Admins update locus object files"
ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'locus-objects' AND public.has_role(auth.uid(), 'admin'))
WITH CHECK (
  bucket_id = 'locus-objects'
  AND public.has_role(auth.uid(), 'admin')
  AND lower(storage.extension(name)) = 'glb'
);

CREATE POLICY "Admins delete locus object files"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'locus-objects' AND public.has_role(auth.uid(), 'admin'));
